# Generated by Django 4.2.11 on 2024-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0002_alter_componente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_cliente', models.CharField(max_length=100)),
                ('nombre_empresa_cliente', models.CharField(max_length=255)),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('telefono_cliente', models.IntegerField()),
                ('email_cliente', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cif_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='datos_contacto_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_empresa_cliente',
        ),
    ]
