# Generated by Django 5.0.3 on 2024-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0003_cliente_remove_pedido_cif_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cif_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
